AWSTemplateFormatVersion: '2010-09-09'
Description: 'ALB that uses pre-created DNS and Certificate resources'

Parameters:
  EnvironmentName:
    Type: String
    Default: "production"
  VpcId:
    Type: AWS::EC2::VPC::Id
  PublicSubnetIds:
    Type: CommaDelimitedList
  ContainerPort:
    Type: Number
    Default: 8080
  ALBSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
  CertificateArn:
    Type: String
  HostedZoneId:
    Type: String
  DomainNameCustom:
    Type: String
    Default: "prod.servicenow123.io"

Resources:
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub ${EnvironmentName}-alb
      Scheme: internet-facing
      Subnets: !Ref PublicSubnetIds
      SecurityGroups:
        - !Ref ALBSecurityGroupId
      Type: application
      IpAddressType: ipv4
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref VpcId
      Port: !Ref ContainerPort
      Protocol: HTTP
      TargetType: instance
      HealthCheckProtocol: HTTP
      HealthCheckPort: !Ref ContainerPort
      HealthCheckPath: /
      Matcher:
        HttpCode: 200

  HTTPSListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Protocol: HTTPS
      Port: 443
      SslPolicy: ELBSecurityPolicy-TLS13-1-2-2021-06
      Certificates:
        - CertificateArn: !Ref CertificateArn
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup

  ALBDNSRecord:
    Type: AWS::Route53::RecordSet
    DependsOn: ApplicationLoadBalancer
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainNameCustom
      Type: A
      AliasTarget:
        DNSName: !GetAtt ApplicationLoadBalancer.DNSName
        HostedZoneId: !GetAtt ApplicationLoadBalancer.CanonicalHostedZoneID

Outputs:
  ALBDnsName:
    Description: 'ALB DNS Name'
    Value: !GetAtt ApplicationLoadBalancer.DNSName
  ALBFinalEndpoint:
    Description: 'Final HTTPS endpoint for users'
    Value: !Sub https://${FullDomainName}
  TargetGroupArn:
    Description: 'Target Group ARN'
    Value: !Ref TargetGroup
