AWSTemplateFormatVersion: '2010-09-09'
Description: 'ALB with cross-account Route53 DNS automation - CORRECTED'

Parameters:
  EnvironmentName:
    Type: String
    Default: "production"
    Description: "Environment name for tagging"
  
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: "VPC ID for the ALB and Target Group"
  
  PublicSubnetIds:
    Type: CommaDelimitedList
    Description: "Comma separated list of public subnet IDs"
  
  ContainerPort:
    Type: Number
    Default: 8080
    Description: "Container port for the target group"
  
  ALBSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: "Security Group ID for ALB"
  
  CertificateArn:
    Type: String
    Description: "ARN of the SSL certificate"
  
  DomainNameCustom:
    Type: String
    Default: "v1.prod.servicenow123.click"
    Description: "Custom domain name for the ALB"
  
  # THIS IS WRONG - FIXED BELOW
  # CrossAccountRoute53RoleArn:
  #   Type: String
  #   Description: "ARN of the IAM role in the DNS account"
  #   Default: "arn:aws:iam::997211577526:role/AuthenticatedRole_Source"  # WRONG!
  
  # CORRECT VERSION:
  CrossAccountRoute53RoleArn:
    Type: String
    Description: "ARN of the IAM role in the DNS account"
    Default: "arn:aws:iam::628125037712:role/AuthenticatedRole"  # CORRECT!
  
  HostedZoneId:
    Type: String
    Default: "Z0668343T3C4U6RNZGN0"
    Description: "Route53 Hosted Zone ID in the DNS account"
  
  HostedZoneName:
    Type: String
    Default: "servicenow123.click"
    Description: "Route53 Hosted Zone name (must end with dot)"

Resources:
  # 1. ALB Resources
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub ${EnvironmentName}-alb
      Scheme: internet-facing
      Subnets: !Ref PublicSubnetIds
      SecurityGroups:
        - !Ref ALBSecurityGroupId
      Type: application
      IpAddressType: ipv4
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Name
          Value: !Sub ${EnvironmentName}-alb

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub ${EnvironmentName}-tg
      VpcId: !Ref VpcId
      Port: !Ref ContainerPort
      Protocol: HTTP
      TargetType: ip
      HealthCheckProtocol: HTTP
      HealthCheckPort: traffic-port
      HealthCheckPath: /
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2
      Matcher:
        HttpCode: "200"
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName

  HTTPSListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Protocol: HTTPS
      Port: 443
      SslPolicy: ELBSecurityPolicy-TLS13-1-2-2021-06
      Certificates:
        - CertificateArn: !Ref CertificateArn
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup
    # NO TAGS HERE - ALB Listener doesn't support tags

  # 2. IAM Role for Lambda - IN YOUR ACCOUNT (997211577526)
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${EnvironmentName}-CrossAccountDNSLambdaRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: AssumeCrossAccountRole
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: sts:AssumeRole
                Resource: !Ref CrossAccountRoute53RoleArn  # DNS account role
        - PolicyName: LambdaBasicExecution
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName

  # 3. Lambda Function for DNS Management
  CreateDNSRecordFunction:
    Type: AWS::Lambda::Function
    DependsOn: LambdaExecutionRole
    Properties:
      FunctionName: !Sub ${EnvironmentName}-CreateDNSRecord
      Description: "Creates Route53 DNS records in another account"
      Runtime: python3.9
      Handler: index.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 300
      MemorySize: 128
      Environment:
        Variables:
          DEBUG: "true"
      Code:
        ZipFile: |
          import boto3
          import json
          import time
          import logging
          import traceback
          import os
          
          logger = logging.getLogger()
          logger.setLevel(logging.INFO)
          
          def assume_role(role_arn, session_name):
              """Assume cross-account role"""
              sts_client = boto3.client('sts')
              try:
                  logger.info(f"Assuming role: {role_arn}")
                  response = sts_client.assume_role(
                      RoleArn=role_arn,
                      RoleSessionName=session_name,
                      DurationSeconds=900
                  )
                  logger.info(f"Successfully assumed role")
                  return response['Credentials']
              except Exception as e:
                  logger.error(f"Failed to assume role: {str(e)}")
                  logger.error(f"Role ARN: {role_arn}")
                  raise
          
          def get_route53_client(credentials):
              """Create Route53 client with assumed role credentials"""
              return boto3.client(
                  'route53',
                  aws_access_key_id=credentials['AccessKeyId'],
                  aws_secret_access_key=credentials['SecretAccessKey'],
                  aws_session_token=credentials['SessionToken']
              )
          
          def lambda_handler(event, context):
              logger.info(f"Event: {json.dumps(event)}")
              
              try:
                  # Import here to avoid packaging issues
                  import cfnresponse
                  
                  properties = event.get('ResourceProperties', {})
                  request_type = event['RequestType']
                  
                  # Get parameters
                  cross_account_role_arn = properties.get('CrossAccountRoleArn')
                  hosted_zone_id = properties.get('HostedZoneId')
                  domain_name = properties.get('DomainName')
                  alb_dns_name = properties.get('ALBDNSName')
                  alb_hosted_zone_id = properties.get('ALBHostedZoneId')
                  
                  logger.info(f"Parameters received:")
                  logger.info(f"  CrossAccountRoleArn: {cross_account_role_arn}")
                  logger.info(f"  HostedZoneId: {hosted_zone_id}")
                  logger.info(f"  DomainName: {domain_name}")
                  logger.info(f"  ALBDNSName: {alb_dns_name}")
                  logger.info(f"  ALBHostedZoneId: {alb_hosted_zone_id}")
                  
                  # Validate
                  if not all([cross_account_role_arn, hosted_zone_id, domain_name, alb_dns_name, alb_hosted_zone_id]):
                      raise ValueError("Missing required parameters")
                  
                  # Ensure domain name ends with dot
                  if not domain_name.endswith('.'):
                      domain_name = domain_name + '.'
                  
                  if not alb_dns_name.endswith('.'):
                      alb_dns_name = alb_dns_name + '.'
                  
                  # Assume role and create DNS record
                  credentials = assume_role(cross_account_role_arn, 'DNSManagementLambda')
                  route53_client = get_route53_client(credentials)
                  
                  change_batch = {
                      'Changes': [{
                          'Action': 'UPSERT',
                          'ResourceRecordSet': {
                              'Name': domain_name,
                              'Type': 'A',
                              'AliasTarget': {
                                  'HostedZoneId': alb_hosted_zone_id,
                                  'DNSName': alb_dns_name,
                                  'EvaluateTargetHealth': True
                              }
                          }
                      }]
                  }
                  
                  logger.info(f"Creating DNS record: {domain_name} -> {alb_dns_name}")
                  response = route53_client.change_resource_record_sets(
                      HostedZoneId=hosted_zone_id,
                      ChangeBatch=change_batch
                  )
                  
                  change_id = response['ChangeInfo']['Id']
                  logger.info(f"DNS change created: {change_id}")
                  
                  # Wait for completion
                  for i in range(60):  # 5 minutes max
                      status_response = route53_client.get_change(Id=change_id)
                      status = status_response['ChangeInfo']['Status']
                      logger.info(f"Change status: {status} (check {i+1}/60)")
                      if status == 'INSYNC':
                          break
                      time.sleep(5)
                  
                  response_data = {
                      'ChangeId': change_id,
                      'DomainName': domain_name,
                      'Message': 'DNS record created successfully'
                  }
                  
                  cfnresponse.send(event, context, cfnresponse.SUCCESS, response_data)
                  
              except Exception as e:
                  error_msg = f"Error: {str(e)}\n{traceback.format_exc()}"
                  logger.error(error_msg)
                  cfnresponse.send(event, context, cfnresponse.FAILED, {'Error': str(e)})

  # 4. Lambda Function Permissions
  LambdaPermission:
    Type: AWS::Lambda::Permission
    DependsOn: CreateDNSRecordFunction
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref CreateDNSRecordFunction
      Principal: cloudformation.amazonaws.com
      SourceAccount: !Ref AWS::AccountId
      SourceArn: !Sub arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/${AWS::StackName}/*

  # 5. Custom Resource for DNS Management
  CrossAccountDNSRecord:
    Type: Custom::CrossAccountDNS
    DependsOn: 
      - ApplicationLoadBalancer
      - CreateDNSRecordFunction
      - LambdaPermission
    Properties:
      ServiceToken: !GetAtt CreateDNSRecordFunction.Arn
      CrossAccountRoleArn: !Ref CrossAccountRoute53RoleArn
      HostedZoneId: !Ref HostedZoneId
      DomainName: !Ref DomainNameCustom
      ALBHostedZoneId: !GetAtt ApplicationLoadBalancer.CanonicalHostedZoneID
      ALBDNSName: !GetAtt ApplicationLoadBalancer.DNSName

Outputs:
  ALBDnsName:
    Description: 'ALB DNS Name'
    Value: !GetAtt ApplicationLoadBalancer.DNSName
  
  ALBFinalEndpoint:
    Description: 'Final HTTPS endpoint for users'
    Value: !Sub https://${DomainNameCustom}
  
  TargetGroupArn:
    Description: 'Target Group ARN'
    Value: !Ref TargetGroup
  
  ALBCanonicalHostedZoneId:
    Description: 'ALB Canonical Hosted Zone ID'
    Value: !GetAtt ApplicationLoadBalancer.CanonicalHostedZoneID