AWSTemplateFormatVersion: '2010-09-09'
Description: 'ECS Cluster with VPC Endpoints'

Parameters:
  EnvironmentName:
    Type: String
  VpcId:
    Type: AWS::EC2::VPC::Id
  PrivateSubnetIds:
    Type: CommaDelimitedList
  ECSSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: 'ECS Security Group ID from VPC stack'
  PrivateRouteTableId:
    Type: String  # CHANGED: Use String type instead
    Description: 'Private Route Table ID from VPC stack (e.g., rtb-xxxxxx)'
    AllowedPattern: '^rtb-[a-z0-9]{8,17}$'  # ADDED: Validation pattern
    ConstraintDescription: 'Must be a valid Route Table ID (rtb-xxxxxx)'
  

Resources:

  # ECS 服务链接角色（必须）
  ECSServiceRole:
    Type: AWS::IAM::ServiceLinkedRole
    Properties:
      AWSServiceName: ecs.amazonaws.com
      Description: Service-linked role for Amazon ECS

  # ECS Cluster
  ECSCluster:
    Type: AWS::ECS::Cluster
    DependsOn: ECSServiceRole  # 确保先创建角色
    Properties:
      ClusterName: !Sub ${EnvironmentName}-cluster
      CapacityProviders:
        - FARGATE
      ClusterSettings:
        - Name: containerInsights
          Value: enabled
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Network
          Value: private-vpce

  # VPC Endpoints (关键！ECS通过这些端点访问AWS服务)

  # 1. ECR API Endpoint (用于认证)
  ECREndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VpcId
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ecr.api  # CORRECT
      VpcEndpointType: Interface
      SubnetIds: !Ref PrivateSubnetIds
      SecurityGroupIds:
        - !Ref ECSSecurityGroupId  # 修改为引用参数
      PrivateDnsEnabled: true
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-ecr-api-endpoint

  # 2. ECR DKR Endpoint (用于拉取镜像)
  ECRDkrEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VpcId
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ecr.dkr  # CORRECT
      VpcEndpointType: Interface
      SubnetIds: !Ref PrivateSubnetIds
      SecurityGroupIds:
        - !Ref ECSSecurityGroupId  # 修改为引用参数
      PrivateDnsEnabled: true
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-ecr-dkr-endpoint

  # 3. S3 Gateway Endpoint (ECR镜像层存储在S3)
  S3Endpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VpcId
      ServiceName: !Sub com.amazonaws.${AWS::Region}.s3
      VpcEndpointType: Gateway
      RouteTableIds:
        - !Ref PrivateRouteTableId  # 修改为引用参数
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: '*'
            Action:
              - s3:GetObject
              - s3:ListBucket
            Resource: '*'
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-s3-endpoint

  # 4. CloudWatch Logs Endpoint
  CloudWatchEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VpcId
      ServiceName: !Sub com.amazonaws.${AWS::Region}.logs
      VpcEndpointType: Interface
      SubnetIds: !Ref PrivateSubnetIds
      SecurityGroupIds:
        - !Ref ECSSecurityGroupId  # 修改为引用参数
      PrivateDnsEnabled: true
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-cloudwatch-endpoint

  # 5. Secrets Manager Endpoint
  SecretsManagerEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VpcId
      ServiceName: !Sub com.amazonaws.${AWS::Region}.secretsmanager
      VpcEndpointType: Interface
      SubnetIds: !Ref PrivateSubnetIds
      SecurityGroupIds:
        - !Ref ECSSecurityGroupId  # 修改为引用参数
      PrivateDnsEnabled: true
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-secretsmanager-endpoint

  # 6. SSM Endpoint (可选，用于调试)
  SSMEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VpcId
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ssm
      VpcEndpointType: Interface
      SubnetIds: !Ref PrivateSubnetIds
      SecurityGroupIds:
        - !Ref ECSSecurityGroupId  # 修改为引用参数
      PrivateDnsEnabled: true
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-ssm-endpoint

Outputs:
  ClusterName:
    Description: 'ECS Cluster Name'
    Value: !Ref ECSCluster
  
  VpcEndpointIds:
    Description: 'VPC Endpoint IDs'
    Value: !Join [',', [
      !Ref ECREndpoint,
      !Ref ECRDkrEndpoint,
      !Ref S3Endpoint,
      !Ref CloudWatchEndpoint,
      !Ref SecretsManagerEndpoint
    ]]