AWSTemplateFormatVersion: '2010-09-09'
Description: 'ServiceNow API - ECR to ECS via VPC Endpoint'

Parameters:
  EnvironmentName:
    Type: String
    Default: production
    Description: 'Environment name'
  
  DomainName:
    Type: String
    Default: api.servicenow-automation.com
    Description: 'Custom domain for HTTPS'
  
  ContainerPort:
    Type: Number
    Default: 8080
    Description: 'Container port'
  
  TemplateBucket:
    Type: String
    Default: my-cfn-templates-bucket-7-12-2025
    Description: 'S3 bucket containing nested templates'

Resources:
  # 1. VPC with isolated private subnets
  VPCStack: 
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${TemplateBucket}.s3.${AWS::Region}.amazonaws.com/vpc-isolated.yaml"
      Parameters:
        EnvironmentName: !Ref EnvironmentName

  # 2. ECS Cluster with VPC Endpoints
  ECSClusterStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${TemplateBucket}.s3.${AWS::Region}.amazonaws.com/ecs-cluster-vpce.yaml"
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        PrivateSubnetIds: !GetAtt VPCStack.Outputs.PrivateSubnetIds
        ECSSecurityGroupId: !GetAtt VPCStack.Outputs.ECSSecurityGroupId
        PrivateRouteTableId: !GetAtt VPCStack.Outputs.PrivateRouteTableId


  # 3. ALB with HTTPS
  ALBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${TemplateBucket}.s3.${AWS::Region}.amazonaws.com/alb-https.yaml"
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        PublicSubnetIds: !GetAtt VPCStack.Outputs.PublicSubnetIds
        DomainName: !Ref DomainName
        ContainerPort: !Ref ContainerPort
        ALBSecurityGroupId: !GetAtt VPCStack.Outputs.ALBSecurityGroupId

  # 4. ECS Service in private subnet
  ECSServiceStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: ALBStack
    Properties:
      TemplateURL: !Sub "https://${TemplateBucket}.s3.${AWS::Region}.amazonaws.com/ecs-service-private.yaml"
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        PrivateSubnetIds: !GetAtt VPCStack.Outputs.PrivateSubnetIds
        ClusterName: !GetAtt ECSClusterStack.Outputs.ClusterName
        TargetGroupArn: !GetAtt ALBStack.Outputs.TargetGroupArn
        ECSSecurityGroupId: !GetAtt VPCStack.Outputs.ECSSecurityGroupId
        ECRRepositoryUri: public.ecr.aws/g1n7j8p0/servicenow_repo
        ContainerPort: !Ref ContainerPort
        DesiredCount: 2
        Cpu: '512'
        Memory: '1024'

Outputs:
  ApiEndpoint:
    Description: 'API HTTPS Endpoint'
    Value: !GetAtt ALBStack.Outputs.ApiEndpoint
  
  ECSClusterName:
    Description: 'ECS Cluster Name'
    Value: !GetAtt ECSClusterStack.Outputs.ClusterName
  
  ECSServiceName:
    Description: 'ECS Service Name'
    Value: !GetAtt ECSServiceStack.Outputs.ServiceName

  DebugRouteTableId:
    Description: 'Debug - PrivateRouteTableId value'
    Value: !GetAtt VPCStack.Outputs.PrivateRouteTableId