AWSTemplateFormatVersion: '2010-09-09'
Description: 'Standalone Route 53 Hosted Zone and Certificate for future ALB'

Parameters:
  EnvironmentName:
    Type: String
    Default: "production"
  VpcId:
    Type: AWS::EC2::VPC::Id
  FullDomainName:
    Type: String
    Default: "service-app.square.site"
    Description: 'The full API domain name (e.g., api.example.com)'
  VPCRegion: 
    Type: String

Resources:
  # 1. 托管区
  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Ref FullDomainName
      HostedZoneConfig:
        Comment: !Sub "Hosted zone for ALB endpoints in ${EnvironmentName}"
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
      VPCs:
        - VPCId: !Ref VpcId
          VPCRegion: !Ref VPCRegion

  # 2. ACM 证书
  SSLCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref FullDomainName
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Ref FullDomainName
          ValidationDomain: !Ref FullDomainName
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName

  # 3. 使用 Custom Resource 等待证书验证记录可用
  CertificateValidationWaiter:
    Type: Custom::CertificateValidationWaiter
    DependsOn: SSLCertificate
    Properties:
      ServiceToken: !GetAtt CertificateValidationLambda.Arn
      CertificateArn: !Ref SSLCertificate
      Timeout: 300

  # 4. 证书验证记录（在等待后创建）
  CertificateValidationRecord:
    Type: AWS::Route53::RecordSet
    DependsOn: CertificateValidationWaiter
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !GetAtt CertificateValidationWaiter.ValidationRecordName
      Type: !GetAtt CertificateValidationWaiter.ValidationRecordType
      TTL: 300
      ResourceRecords:
        - !GetAtt CertificateValidationWaiter.ValidationRecordValue

  # 5. 证书验证
  CertificateValidation:
    Type: AWS::CertificateManager::CertificateValidation
    DependsOn: CertificateValidationRecord
    Properties:
      CertificateArn: !Ref SSLCertificate
      ValidationRecordFqdns:
        - !GetAtt CertificateValidationWaiter.ValidationRecordName

Outputs:
  HostedZoneId:
    Description: 'Route 53 Hosted Zone ID for ALB'
    Value: !Ref HostedZone
    Export:
      Name: !Sub ${EnvironmentName}-HostedZoneId
  NameServers:
    Description: 'Name Servers for ALB'
    Value: !Join [',', !GetAtt HostedZone.NameServers]
  CertificateArn:
    Description: 'Validated ACM Certificate ARN for ALB Listener'
    Value: !Ref SSLCertificate
    Export:
      Name: !Sub ${EnvironmentName}-CertificateArn
  FullDomainNameOutput:
    Description: 'The domain name to be used for ALB'
    Value: !Ref FullDomainName
    Export:
      Name: !Sub ${EnvironmentName}-FullDomainName