AWSTemplateFormatVersion: '2010-09-09'
Description: 'Route 53 Hosted Zone with ACM Certificate'

Parameters:
  EnvironmentName:
    Type: String
    Default: "production"
  VpcId:
    Type: AWS::EC2::VPC::Id
  FullDomainName:
    Type: String
    Default: "servicenow123.io"
  VPCRegion:
    Type:String

Resources:
  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Ref FullDomainName
      VPCs:
        - VPCId: !Ref VpcId
          VPCRegion: !Ref VPCRegion

  SSLCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref FullDomainName
      ValidationMethod: DNS
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName

  WaitForValidation:
    Type: AWS::CloudFormation::CustomResource
    DependsOn: SSLCertificate
    Properties:
      ServiceToken: !GetAtt ValidationWaiterLambda.Arn
      CertificateArn: !Ref SSLCertificate
      Timeout: 600

  ValidationWaiterLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: |
          import json, time, boto3
          def handler(event, context):
            acm = boto3.client('acm')
            cert_arn = event['ResourceProperties']['CertificateArn']
            
            for _ in range(60):
              resp = acm.describe_certificate(CertificateArn=cert_arn)
              validation = resp['Certificate']['DomainValidationOptions'][0]
              if 'ResourceRecord' in validation:
                return {
                  'Data': {
                    'Name': validation['ResourceRecord']['Name'],
                    'Value': validation['ResourceRecord']['Value'],
                    'Type': validation['ResourceRecord']['Type']
                  }
                }
              time.sleep(5)
            raise Exception('Timeout waiting for validation record')

      Handler: index.handler
      Runtime: python3.9
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 300

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: {Service: lambda.amazonaws.com}
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: ACMReadOnly
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: acm:DescribeCertificate
                Resource: "*"

  CertificateValidationRecord:
    Type: AWS::Route53::RecordSet
    DependsOn: WaitForValidation
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: !GetAtt WaitForValidation.Name
      Type: !GetAtt WaitForValidation.Type
      TTL: 300
      ResourceRecords:
        - !GetAtt WaitForValidation.Value

Outputs:
  CertificateArn:
    Description: ACM Certificate ARN
    Value: !Ref SSLCertificate
  
  HostedZoneId:
    Description: Route53 Hosted Zone ID
    Value: !Ref HostedZone
  
  ValidationRecordName:
    Description: Validation record name
    Value: !GetAtt WaitForValidation.Name
  
  ValidationRecordValue:
    Description: Validation record value
    Value: !GetAtt WaitForValidation.Value
