// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistent;

#nullable disable

namespace Persistent.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251023051224_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Domain.Activity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedGroup")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Did_AssignedGroup_Fix_Issue")
                        .HasColumnType("TEXT");

                    b.Property<string>("Duplicate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Duplicate_AI")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ExtraDays_AfterSLAdays")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("Guided_SLAdays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IncidentNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Is_AissignedGroup_ResponsibleTeam")
                        .HasColumnType("TEXT");

                    b.Property<string>("Issue")
                        .HasColumnType("TEXT");

                    b.Property<string>("Issue_AI")
                        .HasColumnType("TEXT");

                    b.Property<string>("LongDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Met_SLA")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberTeam_Fixed_Issue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberTeam_Included_in_Ticket")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OpenDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("OpenDate_Day")
                        .HasColumnType("TEXT");

                    b.Property<string>("OpenDate_Month")
                        .HasColumnType("TEXT");

                    b.Property<string>("OpenDate_Year")
                        .HasColumnType("TEXT");

                    b.Property<string>("Priority")
                        .HasColumnType("TEXT");

                    b.Property<string>("Root_Cause")
                        .HasColumnType("TEXT");

                    b.Property<string>("Root_Cause_AI")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceOwner")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary_Issue")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary_Issue_AI")
                        .HasColumnType("TEXT");

                    b.Property<string>("System")
                        .HasColumnType("TEXT");

                    b.Property<string>("System_AI")
                        .HasColumnType("TEXT");

                    b.Property<string>("Team_Fixed_Issue")
                        .HasColumnType("TEXT");

                    b.Property<string>("Team_Included_in_Ticket")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedDate_Day")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedDate_Month")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedDate_Year")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Activities");
                });
#pragma warning restore 612, 618
        }
    }
}
