// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistent;

#nullable disable

namespace Persistent.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Domain.Activity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedGroup")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Duplicate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Duplicate_AI")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IncidentNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Is_AissignedGroup_ResponsibleTeam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Is_AssignedGroup_Fixed_Issue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Issue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Issue_AI")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LongDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberTeam_Fixed_Issue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberTeam_Included_in_Ticket")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Root_Cause")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary_Issue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary_Issue_AI")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("System")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("System_AI")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Team_Fixed_Issue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Team_Fixed_Issue_AI_Format")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Team_Included_in_Ticket")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Team_Included_in_Ticket_AI_Format")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Activities");
                });
#pragma warning restore 612, 618
        }
    }
}
